# Generated by Django 3.1.5 on 2021-03-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='Comment_rating',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='complain',
            name='Complain_response',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
